secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

account_creation_secret: <%= ENV["ACCOUNT_CREATION_SECRET"] %>

plaid:
  env: development
  client_id: <%= ENV["PLAID_CLIENT_ID"] %>
  public_key: <%= ENV["PLAID_PUBLIC_KEY"] %>
  secret: <%= ENV["PLAID_SECRET"] %>
